# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0005_auto_20170404_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': '航班信息表', 'verbose_name_plural': '航班信息表'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrive_airport',
            field=models.CharField(max_length=100, null=True, verbose_name='到达的机场'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrive_city',
            field=models.CharField(max_length=100, null=True, verbose_name='到达城市'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrive_time',
            field=models.DateTimeField(null=True, verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='book_sum',
            field=models.IntegerField(default=0, null=True, verbose_name='订票总人数'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=0, null=True, verbose_name='座位总数'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='income',
            field=models.FloatField(default=0, null=True, verbose_name='收入'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='leave_airport',
            field=models.CharField(max_length=100, null=True, verbose_name='离开的机场'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='leave_city',
            field=models.CharField(max_length=100, null=True, verbose_name='离开城市'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='leave_time',
            field=models.DateTimeField(null=True, verbose_name='离开时间'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=100, verbose_name='班次'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='价格'),
        ),
        migrations.AlterModelTable(
            name='flight',
            table='Flight',
        ),
    ]
