# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-18 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksystem', '0006_auto_20200418_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='英文名')),
                ('sex', models.CharField(default='男', max_length=50, verbose_name='性别')),
                ('age', models.CharField(max_length=50, null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='手机号码')),
                ('sfz', models.CharField(max_length=50, null=True, verbose_name='身份证号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
