# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0009_auto_20200418_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=50, verbose_name='性别'),
        ),
    ]
